name: Deployment of Project Management

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          composer dump-autoload
          npm ci
          npm run build
          php artisan config:clear

      - name: Copy Environment File
        run: |
          cp .env.projectmanagement .env

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        run: |
          # Sync new files to the server
          sshpass -p 'c#)rgPMzNC2998@Vb4.M' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@147.93.30.80:/var/www/project-management/

          sshpass -p 'c#)rgPMzNC2998@Vb4.M' ssh -o StrictHostKeyChecking=no root@147.93.30.80 << 'EOF'
            cd /var/www/project-management

            # PERBAIKAN 1: Clear everything first before setting permissions
            php8.2 artisan down --message="Upgrading Application" --allow=147.93.30.80

            # PERBAIKAN 2: Remove problematic cache files
            rm -rf storage/framework/cache/data/*
            rm -rf storage/framework/views/*
            rm -rf storage/framework/sessions/*
            rm -rf storage/logs/*
            rm -rf bootstrap/cache/*.php

            # PERBAIKAN 3: Recreate necessary directories
            mkdir -p storage/framework/cache/data
            mkdir -p storage/framework/views
            mkdir -p storage/framework/sessions
            mkdir -p storage/logs
            mkdir -p bootstrap/cache

            # PERBAIKAN 4: Set ownership BEFORE running Laravel commands
            chown -R www-data:www-data /var/www/project-management
            chmod -R 755 /var/www/project-management
            chmod -R 775 /var/www/project-management/storage
            chmod -R 775 /var/www/project-management/bootstrap/cache

            # PERBAIKAN 5: Laravel Commands in correct order
            php8.2 artisan key:generate --ansi --force
            php8.2 artisan config:clear
            php8.2 artisan cache:clear
            php8.2 artisan route:clear
            php8.2 artisan view:clear
            php8.2 artisan storage:link --force

            # PERBAIKAN 6: Run migrations AFTER clearing cache
            php8.2 artisan migrate --force

            # PERBAIKAN 7: Optimize for production
            php8.2 artisan config:cache
            php8.2 artisan route:cache
            php8.2 artisan view:cache

            # PERBAIKAN 8: Final permission fix
            chown -R www-data:www-data /var/www/project-management
            chmod -R 775 /var/www/project-management/storage /var/www/project-management/bootstrap/cache

            # PERBAIKAN 9: Bring application back up
            php8.2 artisan up

          EOF
